### ISSUE TITLE
run time error cameraview not initialized issue

### ISSUE THREAD

**Issue by AsadDev40** [chenyeju295/flutter_uvc_camera#17]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, lateinit property cameraView has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property cameraView has not been initialized.
  StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (17930): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (17930): <asynchronous suspension>
E/flutter (17930): #2      UVCCameraController.openUVCCamera (package:flutter_uvc_camera/uvc_camera_controller.dart:88:5)
E/flutter (17930): <asynchronous suspension>
E/flutter (17930): #3      _CameraTestState.build.<anonymous closure> (package:usb_camera/main.dart:64:19)
E/flutter (17930): <asynchronous suspension>

**Comment by chenyeju295** [comment]
@AsadDev40 Hi, can you look at the write-up when used?
