### ISSUE TITLE
Android API > 10 have a issue preview failed?

### ISSUE THREAD

**Issue by hsyani** [chenyeju295/flutter_uvc_camera#19]
any one has same issue?

Launching lib\main.dart on TB330FU in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:53044/3Il17MPh3I4=/ws
D/DecorView(19229): isCts, pkg: com.example.camera_ir2
I/mali    (19229): [DebugProp] GPU Debug-Mechanism Disable !
D/hw-ProcessState(19229): Binder ioctl to enable oneway spam detection failed: Invalid argument
D/BLASTBufferQueue(19229): [SurfaceView[com.example.camera_ir2/com.example.camera_ir2.MainActivity]#1](f:0,a:1) acquireNextBufferLocked size=1920x1177 mFrameNumber=1 applyTransaction=true mTimestamp=5912598863812(auto) mPendingTransactions.size=0 graphicBufferId=82587926134784 transform=7
D/BLASTBufferQueue(19229): [VRI[MainActivity]#0](f:0,a:1) acquireNextBufferLocked size=1920x1200 mFrameNumber=1 applyTransaction=true mTimestamp=5912617517043(auto) mPendingTransactions.size=0 graphicBufferId=82587926134785 transform=7
W/Parcel  (19229): Expecting binder but got null!
D/DecorView(19229): isCts, pkg: com.example.camera_ir2
I/flutter (19229): ------> UVCCameraController init
[log] start init
I/PlatformViewsController(19229): Hosting view in view hierarchy for platform view: 0
[log] Permission.storage is grandted
I/PlatformViewsController(19229): PlatformView is using ImageReader backend
D/BufferQueueConsumer(19229): [](id:4b1d00000002,api:0,p:-1,c:19229) connect: controlledByApp=true
W/OnBackInvokedCallback(19229): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback(19229): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
I/libPerfCtl(19229): xgfNotifyBufferQuota ret=-1
W/binder:19229_1(19229): type=1400 audit(0.0:3014): avc: denied { ioctl } for path="/proc/perfmgr/perf_ioctl" dev="proc" ino=4026532626 ioctlcmd=0x6718 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:proc_perfmgr:s0 tclass=file permissive=0 app=com.example.camera_ir2
D/Surface (19229): lockHardwareCanvas
E/FrameEvents(19229): updateAcquireFence: Did not find frame.
W/Parcel  (19229): Expecting binder but got null!
W/mple.camera_ir2(19229): type=1400 audit(0.0:3015): avc: denied { ioctl } for path="/proc/perfmgr/perf_ioctl" dev="proc" ino=4026532626 ioctlcmd=0x6717 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:proc_perfmgr:s0 tclass=file permissive=0 app=com.example.camera_ir2
[log] Permission.camera is grandted
D/Surface (19229): lockHardwareCanvas
D/TextureView(19229): getHardwareLayer, createNewSurface:true
D/BufferQueueConsumer(19229): [](id:4b1d00000003,api:0,p:-1,c:19229) connect: controlledByApp=true
V/USBMonitor(19229): USBMonitor:Constructor
V/USBMonitor(19229): USBMonitor:mUsbManager=android.hardware.usb.UsbManager@d3a66c4
I/MultiCameraClient(19229): register...
I/USBMonitor(19229): register:
E/FrameEvents(19229): updateAcquireFence: Did not find frame.
[log] Permission.microphone is grandted
D/DecorView(19229): isCts, pkg: com.example.camera_ir2
D/Surface (19229): lockHardwareCanvas
[log] Permission.audio is grandted
E/FrameEvents(19229): updateAcquireFence: Did not find frame.
E/ImageTextureRegistryEntry(19229): Dropping PlatformView Frame
D/CompatibilityChangeReporter(19229): Compat change id reported: 78294732; UID 10249; state: DISABLED
V/USBMonitor(19229): USBMonitor:Constructor
V/USBMonitor(19229): USBMonitor:mUsbManager=android.hardware.usb.UsbManager@d3a66c4
I/MultiCameraClient(19229): register...
I/USBMonitor(19229): register:
D/DecorView(19229): isCts, pkg: com.example.camera_ir2
I/MultiCameraClient(19229): attach device name/pid/vid:/dev/bus/usb/001/007&8838&7119
I/USBMonitor(19229): request permission, has permission: true
V/USBMonitor(19229): processConnect:device=/dev/bus/usb/001/007
I/USBMonitor(19229): UsbControlBlock:constructor
D/UsbDeviceConnectionJNI(19229): close
I/USBMonitor(19229): name=/dev/bus/usb/001/007,desc=188,busnum=1,devnum=7,rawDesc=
I/MultiCameraClient(19229): connect device name/pid/vid:/dev/bus/usb/001/007&8838&7119
I/CameraView(19229): camera connection. pid: 8838, vid: 7119
I/AspectRatioTextureView(19229): AspectRatio = 1.3333333333333333
I/MultiCameraClient(19229): surface measure size (484, 363)
D/Surface (19229): lockHardwareCanvas
E/FrameEvents(19229): updateAcquireFence: Did not find frame.
I/RenderManager(19229): create RenderManager, Open ES version is 3.2
D/libMEOW (19229): meow new tls: 0x6f32ed2080
D/libMEOW (19229): applied 0 plugin for [com.example.camera_ir2].
D/libMEOW (19229): rebuild call chain: 0x6f32fd1c00
I/EGLEvn  (19229): Init EGL Success!
I/EGLEvn  (19229): setupSurface Success!
I/AbstractRender(19229): init surface texture render success!
I/AbstractRender(19229): create external texture, id = 1
I/AbstractRender(19229): init surface texture render success!
I/AbstractRender(19229): init surface texture render success!
D/BufferQueueConsumer(19229): [](id:4b1d00000004,api:0,p:-1,c:19229) connect: controlledByApp=true
D/UsbDeviceConnectionJNI(19229): close
I/libusb/core(19229): [19301*core.c:2085:libusb_init2]:libusb v1.0.19.10903
I/libusb/usbfs(19229): [19301*android_usbfs.c:504:op_init2]:start up hotplug event handler
I/libusb/usbfs(19229): [19301*android_usbfs.c:512:op_init2]:call android_scan_devices
I/UVCCamera(19229): open camera status: 477581308544, size: {"formats":[{"index":1,"type":6,"default":1,"size":["1920x1080","1600x896","1280x720","1024x768","1024x576","960x544","864x480","848x480","800x448","640x480","640x360","352x288","320x240"]},{"index":2,"type":4,"default":1,"size":["640x480","1920x1080","1600x896","1280x720","1024x768","960x544","864x480","848x480","800x448","640x360","352x288","320x240"]}]}
I/MultiCameraClient(19229): attach device name/pid/vid:/dev/bus/usb/001/007&8838&7119
I/CameraUVC(19229): aspect ratio = null, getAllPreviewSizes = [PreviewSize(width=1920, height=1080), PreviewSize(width=1600, height=896), PreviewSize(width=1280, height=720), PreviewSize(width=1024, height=768), PreviewSize(width=1024, height=576), PreviewSize(width=960, height=544), PreviewSize(width=864, height=480), PreviewSize(width=848, height=480), PreviewSize(width=800, height=448), PreviewSize(width=640, height=480), PreviewSize(width=640, height=360), PreviewSize(width=352, height=288), PreviewSize(width=320, height=240)],
I/CameraUVC(19229): getSuitableSize: PreviewSize(width=640, height=480)
I/CameraUVC(19229): aspect ratio = null, getAllPreviewSizes = [PreviewSize(width=1920, height=1080), PreviewSize(width=1600, height=896), PreviewSize(width=1280, height=720), PreviewSize(width=1024, height=768), PreviewSize(width=1024, height=576), PreviewSize(width=960, height=544), PreviewSize(width=864, height=480), PreviewSize(width=848, height=480), PreviewSize(width=800, height=448), PreviewSize(width=640, height=480), PreviewSize(width=640, height=360), PreviewSize(width=352, height=288), PreviewSize(width=320, height=240)],
I/MultiCameraClient(19229): Audio record by using system mic
I/libUVCCamera(19229): [19304*UVCPreview.cpp:509:prepare_preview]:frameSize=(640,480)@YUYV
I/libUVCCamera(19229): [19306*UVCPreview.cpp:267:callbackPixelFormatChanged]:PIXEL_FORMAT_RAW:
I/CameraUVC(19229):  start preview, name = /dev/bus/usb/001/007, preview=PreviewSize(width=640, height=480)
I/CameraView(19229): ------>CameraState: OPENED
I/RenderManager(19229): create camera SurfaceTexture: android.graphics.SurfaceTexture@756828c
I/AbstractRender(19229): create texture, id = 2
I/flutter (19229): Camera: OPENED
I/AbstractFboRender(19229): load fbo, textures: [I@fe46dd5, buffers: [I@577d9ea
I/AbstractRender(19229): create texture, id = 3
I/AbstractFboRender(19229): load fbo, textures: [I@d6944db, buffers: [I@52f3b78
I/flutter (19229): openUVCCamera
D/DecorView(19229): isCts, pkg: com.example.camera_ir2
V/USBMonitor(19229): USBMonitor:Constructor
V/USBMonitor(19229): USBMonitor:mUsbManager=android.hardware.usb.UsbManager@d3a66c4
I/MultiCameraClient(19229): register...
I/USBMonitor(19229): register:
D/DecorView(19229): isCts, pkg: com.example.camera_ir2
I/MultiCameraClient(19229): attach device name/pid/vid:/dev/bus/usb/001/007&8838&7119
W/System.err(19229): java.util.concurrent.TimeoutException: Timeout waiting for task.
W/System.err(19229): 	at com.jiangdg.ausbc.utils.SettableFuture$Sync.get(SettableFuture.kt:85)
W/System.err(19229): 	at com.jiangdg.ausbc.utils.SettableFuture.get(SettableFuture.kt:47)
W/System.err(19229): 	at com.jiangdg.ausbc.MultiCameraClient$ICamera.handleMessage(MultiCameraClient.kt:322)
W/System.err(19229): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(19229): 	at android.os.Looper.loopOnce(Looper.java:201)
W/System.err(19229): 	at android.os.Looper.loop(Looper.java:288)
W/System.err(19229): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/MultiCameraClient(19229): surface measure size null
I/RenderManager(19229): create RenderManager, Open ES version is 3.2
D/libMEOW (19229): meow new tls: 0x6f321cc4c0
D/libMEOW (19229): applied 0 plugin for [com.example.camera_ir2].
D/libMEOW (19229): rebuild call chain: 0x6f321db180
I/EGLEvn  (19229): Init EGL Success!
E/BufferQueueProducer(19229): [SurfaceTexture-0-19229-0](id:4b1d00000003,api:1,p:19229,c:19229) connect: already connected (cur=1 req=1)
E/libEGL  (19229): eglCreateWindowSurface: native_window_api_connect (win=0x6f32e18010) failed (0xffffffea) (already connected to another API?)
E/libEGL  (19229): eglCreateWindowSurfaceTmpl:705 error 3003 (EGL_BAD_ALLOC)
E/EGLEvn  (19229): Create window failed. error = 12291
I/EGLEvn  (19229): setupSurface Success!
I/AbstractRender(19229): init surface texture render success!
I/AbstractRender(19229): create external texture, id = 1
I/AbstractRender(19229): init surface texture render success!
I/AbstractRender(19229): init surface texture render success!
D/BufferQueueConsumer(19229): [](id:4b1d00000005,api:0,p:-1,c:19229) connect: controlledByApp=true
D/UsbDeviceConnectionJNI(19229): close
I/libusb/core(19229): [19318*core.c:2085:libusb_init2]:libusb v1.0.19.10903
I/libusb/usbfs(19229): [19318*android_usbfs.c:512:op_init2]:call android_scan_devices
E/libusb/usbfs(19229): [19318*android_usbfs.c:1776:release_interface]:release interface failed, error -1 errno 22
E/UVCCamera(19229): [19318*UVCCamera.cpp:172:connect]:could not open camera:err=-99
I/CameraView(19229): ------>CameraState: ERROR
E/CameraUVC(19229): open camera failed.
E/CameraUVC(19229): java.lang.UnsupportedOperationException: open failed:result=-99----->id_camera=477591159808;venderId=7119;productId=8838;fileDescriptor=243;busNum=1;devAddr=7;usbfs=/dev/bus/usb
E/CameraUVC(19229): Exception：调用nativeConnect返回值：-99
E/CameraUVC(19229): 	at com.jiangdg.uvc.UVCCamera.open(UVCCamera.java:217)
E/CameraUVC(19229): 	at com.chenyeju.CameraUVC.openCameraInternal(CustomCameraUVC.kt:129)
E/CameraUVC(19229): 	at com.jiangdg.ausbc.MultiCameraClient$ICamera$handleMessage$1$1.onSurfaceTextureAvailable(MultiCameraClient.kt:345)
E/CameraUVC(19229): 	at com.jiangdg.ausbc.render.RenderManager.startRenderScreen(RenderManager.kt:269)
E/CameraUVC(19229): 	at com.jiangdg.ausbc.MultiCameraClient$ICamera.handleMessage(MultiCameraClient.kt:338)
E/CameraUVC(19229): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/CameraUVC(19229): 	at android.os.Looper.loopOnce(Looper.java:201)
E/CameraUVC(19229): 	at android.os.Looper.loop(Looper.java:288)
E/CameraUVC(19229): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (19229): Camera: ERROR:open camera failed open failed:result=-99----->id_camera=477591159808;venderId=7119;productId=8838;fileDescriptor=243;busNum=1;devAddr=7;usbfs=/dev/bus/usb
I/flutter (19229): Exception：调用nativeConnect返回值：-99
I/CameraUVC(19229): aspect ratio = null, getAllPreviewSizes = [PreviewSize(width=1920, height=1080), PreviewSize(width=1600, height=896), PreviewSize(width=1280, height=720), PreviewSize(width=1024, height=768), PreviewSize(width=1024, height=576), PreviewSize(width=960, height=544), PreviewSize(width=864, height=480), PreviewSize(width=848, height=480), PreviewSize(width=800, height=448), PreviewSize(width=640, height=480), PreviewSize(width=640, height=360), PreviewSize(width=352, height=288), PreviewSize(width=320, height=240)],
I/CameraUVC(19229): getSuitableSize: PreviewSize(width=640, height=480)
I/CameraUVC(19229): aspect ratio = null, getAllPreviewSizes = [PreviewSize(width=1920, height=1080), PreviewSize(width=1600, height=896), PreviewSize(width=1280, height=720), PreviewSize(width=1024, height=768), PreviewSize(width=1024, height=576), PreviewSize(width=960, height=544), PreviewSize(width=864, height=480), PreviewSize(width=848, height=480), PreviewSize(width=800, height=448), PreviewSize(width=640, height=480), PreviewSize(width=640, height=360), PreviewSize(width=352, height=288), PreviewSize(width=320, height=240)],
I/MultiCameraClient(19229): Audio record by using system mic
I/CameraUVC(19229):  start preview, name = /dev/bus/usb/001/007, preview=PreviewSize(width=640, height=480)
I/CameraView(19229): ------>CameraState: OPENED
I/RenderManager(19229): create camera SurfaceTexture: android.graphics.SurfaceTexture@932919a
I/AbstractRender(19229): create texture, id = 2
W/Looper  (19229): Slow dispatch took 2137ms camera-1717406953651 h=android.os.Handler c=null m=1
I/AbstractFboRender(19229): load fbo, textures: [I@a011acb, buffers: [I@ca472a8
I/AbstractRender(19229): create texture, id = 3
I/CameraView(19229): ------>CameraState: CLOSED
I/AbstractFboRender(19229): load fbo, textures: [I@2e431c1, buffers: [I@e982d66
E/ion     (19229): ioctl c0044901 failed with code -1: Invalid argument
I/DMABUFHEAPS(19229): Using : Legacy ion heaps
I/USBMonitor(19229): UsbControlBlock#close:
D/UsbDeviceConnectionJNI(19229): close
I/MultiCameraClient(19229): disconnect device name/pid/vid:/dev/bus/usb/001/007&8838&7119
I/CameraUVC(19229):  stop preview, name = /dev/bus/usb/001/007
E/libEGL  (19229): eglPresentationTimeANDROIDImpl:2226 error 300d (EGL_BAD_SURFACE)
E/EGLEvn  (19229): Set Presentation time failed. error = 12301
E/libEGL  (19229): eglSwapBuffersWithDamageKHRImpl:1357 error 300d (EGL_BAD_SURFACE)
E/EGLEvn  (19229): Swap buffers failed. error = 12301
I/AbstractRender(19229): release surface texture render success!
E/libEGL  (19229): eglDestroySurfaceImpl:873 error 300d (EGL_BAD_SURFACE)
I/EGLEvn  (19229): Release EGL Success!
I/AbstractRender(19229): release surface texture render success!
E/libEGL  (19229): call to OpenGL ES API with no current context (logged once per thread)
I/AbstractRender(19229): release surface texture render success!
D/libMEOW (19229): meow delete tls: 0x6f321cc4c0
I/flutter (19229): Camera: OPENED
I/flutter (19229): Camera: CLOSED

**Comment by chenyeju295** [comment]
@hsyani  Hi! See if that's the case.issuse: #14

**Comment by sateshkumar** [comment]
When there is PIXEL_FORMAT_RAW, the terminal device doesn't support preview.
