### ISSUE TITLE
Missing required view with ID

### ISSUE THREAD

**Issue by alexbrtz** [chenyeju295/flutter_uvc_camera#32]
Tengo el siguiente error en mi aplicacion flutter 

Intente crear el layaut **fragment_container** pero solo muestra una imagen negra
->Segun el log, la conexion con el puerto USB  /dev/bus/usb/001/012 Venus USB2.0 Camera fue exitosa pero aun asi solo muestra un cuadro negro 
```
I/MultiCameraClient(12871): connect device name/pid/vid:/dev/bus/usb/001/012&13392&2760 
I/CameraView(12871): camera connection. pid: 13392, vid: 2760
I/libusb/core(12871): [4613*core.c:2085:libusb_init2]:libusb v1.0.19.10903
I/libusb/usbfs(12871): [4613*android_usbfs.c:504:op_init2]:start up hotplug event handler
I/libusb/usbfs(12871): [4613*android_usbfs.c:512:op_init2]:call android_scan_devices
I/UVCCamera(12871): open camera status: 125332850456208, size: {"formats":[{"index":1,"type":4,"default":1,"size":["640x480","352x288","320x240","176x144","160x120"]}]}
I/CameraUVC(12871): aspect ratio = null, getAllPreviewSizes = [PreviewSize(width=640, height=480), PreviewSize(width=352, height=288), PreviewSize(width=320, height=240), PreviewSize(width=176, height=144), PreviewSize(width=160, height=120)], 
I/CameraUVC(12871): getSuitableSize: PreviewSize(width=640, height=480)
I/CameraUVC(12871): aspect ratio = null, getAllPreviewSizes = [PreviewSize(width=640, height=480), PreviewSize(width=352, height=288), PreviewSize(width=320, height=240), PreviewSize(width=176, height=144), PreviewSize(width=160, height=120)], 
I/MultiCameraClient(12871): Audio record by using system mic
E/libUVCCamera(12871): [4618*UVCPreview.cpp:524:prepare_preview]:could not negotiate with camera:err=-51
I/CameraView(12871): ------>CameraState: OPENED
```

-> Este error muestra cuando el layaut **fragment_container** no existe en mi proyecto 
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Missing required view with ID: com.my.app:id/fragment_container, null, java.lang.NullPointerException: Missing required view with ID: com.my.app:id/fragment_container
	at com.chenyeju.databinding.ActivityMainBinding.bind(ActivityMainBinding.java:67)
	at com.chenyeju.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:49)
	at com.chenyeju.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:39)
	at com.chenyeju.UVCCameraView.<init>(UVCCameraView.kt:54)
	at com.chenyeju.UVCCameraViewFactory.create(UVCCameraViewFactory.kt:14)
	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:527)
	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:199)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
)
```

**Comment by chenyeju295** [comment]
@alexbrtz Hi! See if that's the case.issuse: #14
